<?php
define('_DB_SERVER_', 'localhost:3306');
define('_DB_NAME_', 'ps_kokoromoda');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', 'root');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'yjyI50CUrbMPyDm6pEKyZuA9gucENeah2BwfCpscwsNkPSSybYNVfb4P');
define('_COOKIE_IV_', 'e7myy1Wq');
define('_PS_CREATION_DATE_', '2014-11-22');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'eOvRSIG6jwxOUeRfwaX5HtAssjEoGObj');
define('_RIJNDAEL_IV_', 'F2li2LGkxwnq1xXJMlR0yA==');
